/*
 * Copyright (c) 2026 The XGo Authors (xgo.dev). All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package initpkg

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// fileOnDisk reads a file from dir's working tree and reports whether it exists.
func fileOnDisk(t *testing.T, dir, name string) (string, bool) {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(dir, name))
	if err != nil {
		return "", false
	}
	return string(data), true
}

// badgeBlock is the exact four-line block that must appear for module, joined
// with the given newline, used to assert on the inserted text.
func badgeBlock(module, nl string) string {
	return strings.Join(badgeLines(module), nl)
}

// -----------------------------------------------------------------------------
// Unit tests for insertBadges: the pure text transform.

func TestInsertBadges_ATXTitle(t *testing.T) {
	in := "# cjson\n\nGo bindings for the cJSON library, generated by llcppg.\n"
	out, ok := insertBadges(in, "cjson")
	if !ok {
		t.Fatal("expected a title to be found")
	}
	want := "# cjson\n\n" + badgeBlock("cjson", "\n") + "\n\nGo bindings for the cJSON library, generated by llcppg.\n"
	if out != want {
		t.Errorf("insertBadges mismatch:\n got:\n%q\nwant:\n%q", out, want)
	}
}

func TestInsertBadges_ATXTitleClosingHashes(t *testing.T) {
	in := "# cjson #\n\nText.\n"
	out, ok := insertBadges(in, "cjson")
	if !ok {
		t.Fatal("expected a title to be found")
	}
	if !strings.HasPrefix(out, "# cjson #\n\n[![GoDoc]") {
		t.Errorf("badges not placed after a closing-hash title:\n%q", out)
	}
}

func TestInsertBadges_ATXTitleLeadingSpaces(t *testing.T) {
	in := "   # cjson\n\nText.\n"
	if _, ok := insertBadges(in, "cjson"); !ok {
		t.Error("up to three leading spaces before '#' should still be a title")
	}
}

func TestInsertBadges_SetextTitle(t *testing.T) {
	in := "cjson\n=====\n\nSome text.\n"
	out, ok := insertBadges(in, "cjson")
	if !ok {
		t.Fatal("expected a setext title to be found")
	}
	want := "cjson\n=====\n\n" + badgeBlock("cjson", "\n") + "\n\nSome text.\n"
	if out != want {
		t.Errorf("insertBadges setext mismatch:\n got:\n%q\nwant:\n%q", out, want)
	}
	// The title text and its underline must stay adjacent.
	if !strings.Contains(out, "cjson\n=====\n") {
		t.Errorf("title and underline were separated:\n%q", out)
	}
}

func TestInsertBadges_MultiLineSetextTitle(t *testing.T) {
	in := "cjson\nbindings\n=====\n\nText.\n"
	out, ok := insertBadges(in, "cjson")
	if !ok {
		t.Fatal("expected a multi-line setext title to be found")
	}
	// The block goes after the underline, not between the text and the underline.
	if !strings.Contains(out, "cjson\nbindings\n=====\n\n[![GoDoc]") {
		t.Errorf("block not placed after a multi-line setext underline:\n%q", out)
	}
}

func TestInsertBadges_NoBlankLineAfterTitle(t *testing.T) {
	// Title immediately followed by text, no blank line: the result must have
	// exactly one blank line on each side of the block.
	in := "# cjson\nText right after.\n"
	out, ok := insertBadges(in, "cjson")
	if !ok {
		t.Fatal("expected a title to be found")
	}
	want := "# cjson\n\n" + badgeBlock("cjson", "\n") + "\n\nText right after.\n"
	if out != want {
		t.Errorf("mismatch with no original blank line:\n got:\n%q\nwant:\n%q", out, want)
	}
}

func TestInsertBadges_SeveralBlankLinesAfterTitle(t *testing.T) {
	// Several blank lines after the title must collapse to exactly one on the
	// trailing side of the block.
	in := "# cjson\n\n\n\nText.\n"
	out, ok := insertBadges(in, "cjson")
	if !ok {
		t.Fatal("expected a title to be found")
	}
	want := "# cjson\n\n" + badgeBlock("cjson", "\n") + "\n\nText.\n"
	if out != want {
		t.Errorf("blank lines not collapsed:\n got:\n%q\nwant:\n%q", out, want)
	}
}

func TestInsertBadges_TitleOnlyFile(t *testing.T) {
	// A file that is only a title (with trailing newline): badges follow, with a
	// single blank line between, and the trailing newline is preserved.
	in := "# cjson\n"
	out, ok := insertBadges(in, "cjson")
	if !ok {
		t.Fatal("expected a title to be found")
	}
	want := "# cjson\n\n" + badgeBlock("cjson", "\n") + "\n"
	if out != want {
		t.Errorf("title-only mismatch:\n got:\n%q\nwant:\n%q", out, want)
	}
}

func TestInsertBadges_FrontMatterBeforeTitle(t *testing.T) {
	in := "---\ntitle: cjson\n---\n\n# cjson\n\nText.\n"
	out, ok := insertBadges(in, "cjson")
	if !ok {
		t.Fatal("front matter should be skipped and the title found")
	}
	if !strings.Contains(out, "# cjson\n\n[![GoDoc]") {
		t.Errorf("badges not placed after the title following front matter:\n%q", out)
	}
	// The front matter is untouched.
	if !strings.HasPrefix(out, "---\ntitle: cjson\n---\n") {
		t.Errorf("front matter was altered:\n%q", out)
	}
}

func TestInsertBadges_HTMLCommentBeforeTitle(t *testing.T) {
	in := "<!-- a comment -->\n\n# cjson\n\nText.\n"
	out, ok := insertBadges(in, "cjson")
	if !ok {
		t.Fatal("an HTML comment before the title should be skipped")
	}
	if !strings.Contains(out, "# cjson\n\n[![GoDoc]") {
		t.Errorf("badges not placed after the title following a comment:\n%q", out)
	}
}

func TestInsertBadges_CodeFenceHeadingIgnored(t *testing.T) {
	// A "# comment" inside a fenced code block is not a heading; the real title
	// comes after the fence.
	in := "```\n# not a title\n```\n\n# cjson\n\nText.\n"
	out, ok := insertBadges(in, "cjson")
	if !ok {
		t.Fatal("expected the real title after the code fence")
	}
	if !strings.Contains(out, "```\n# not a title\n```\n\n# cjson\n\n[![GoDoc]") {
		t.Errorf("badges placed at the wrong title:\n%q", out)
	}
}

func TestInsertBadges_TildeCodeFenceHeadingIgnored(t *testing.T) {
	in := "~~~\n# not a title\n~~~\n\n# cjson\n\nText.\n"
	out, ok := insertBadges(in, "cjson")
	if !ok {
		t.Fatal("expected the real title after the ~~~ code fence")
	}
	if !strings.Contains(out, "~~~\n\n# cjson\n\n[![GoDoc]") {
		t.Errorf("badges placed at the wrong title:\n%q", out)
	}
}

func TestInsertBadges_Level2BeforeLevel1(t *testing.T) {
	// A level-2 heading (## and --- underline) before any level-1 heading must be
	// ignored; the later level-1 heading wins.
	in := "## Usage\n\nsub\n---\n\n# cjson\n\nText.\n"
	out, ok := insertBadges(in, "cjson")
	if !ok {
		t.Fatal("expected the later level-1 heading to be used")
	}
	if !strings.Contains(out, "# cjson\n\n[![GoDoc]") {
		t.Errorf("badges not placed at the level-1 heading:\n%q", out)
	}
	// Nothing was inserted at the level-2 material.
	if strings.Contains(out, "## Usage\n\n[![GoDoc]") {
		t.Errorf("badges wrongly inserted at a level-2 heading:\n%q", out)
	}
}

func TestInsertBadges_HTMLTitleNotRecognized(t *testing.T) {
	in := `<h1 align="center">cjson</h1>` + "\n\nText.\n"
	if out, ok := insertBadges(in, "cjson"); ok {
		t.Errorf("an HTML <h1> title must not be recognized, got:\n%q", out)
	}
}

func TestInsertBadges_NoTitle(t *testing.T) {
	in := "Just some text with no heading at all.\n\nMore text.\n"
	if _, ok := insertBadges(in, "cjson"); ok {
		t.Error("a file with no heading must report no title")
	}
}

func TestInsertBadges_CRLF(t *testing.T) {
	in := "# cjson\r\n\r\nText.\r\n"
	out, ok := insertBadges(in, "cjson")
	if !ok {
		t.Fatal("expected a title to be found in a CRLF file")
	}
	want := "# cjson\r\n\r\n" + badgeBlock("cjson", "\r\n") + "\r\n\r\nText.\r\n"
	if out != want {
		t.Errorf("CRLF handling mismatch:\n got:\n%q\nwant:\n%q", out, want)
	}
	// No lone LF badge separators crept in.
	if strings.Contains(strings.ReplaceAll(out, "\r\n", ""), "\n") {
		t.Errorf("a lone LF leaked into a CRLF file:\n%q", out)
	}
}

func TestInsertBadges_NoTrailingNewlinePreserved(t *testing.T) {
	// A title-only file with no trailing newline: the output must also lack a
	// trailing newline, while the title still gets a newline so the badges sit on
	// their own lines.
	in := "# cjson"
	out, ok := insertBadges(in, "cjson")
	if !ok {
		t.Fatal("expected a title to be found")
	}
	want := "# cjson\n\n" + badgeBlock("cjson", "\n")
	if out != want {
		t.Errorf("trailing-newline handling mismatch:\n got:\n%q\nwant:\n%q", out, want)
	}
	if strings.HasSuffix(out, "\n") {
		t.Errorf("a trailing newline was added where the original had none:\n%q", out)
	}
}

func TestInsertBadges_ModuleNameInEveryBadgeURL(t *testing.T) {
	out, ok := insertBadges("# zlib\n\nText.\n", "zlib")
	if !ok {
		t.Fatal("expected a title to be found")
	}
	// The module name must appear, with the fixed org name, in every URL of the
	// GoDoc and release badges: the badge image and link of each (four URLs).
	for _, want := range []string{
		"https://pkg.go.dev/badge/github.com/llarhub/zlib.svg",
		"https://pkg.go.dev/github.com/llarhub/zlib",
		"https://img.shields.io/github/v/tag/llarhub/zlib.svg?label=release",
		"https://github.com/llarhub/zlib/releases",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("expected URL %q in badges:\n%s", want, out)
		}
	}
	// The LLGo and XGo badges are fixed and carry no module name.
	if !strings.Contains(out, "https://github.com/xgo-dev/llgo") ||
		!strings.Contains(out, "https://github.com/goplus/xgo") {
		t.Errorf("fixed LLGo/XGo badge URLs missing:\n%s", out)
	}
}

// -----------------------------------------------------------------------------
// addReadmeBadges: the file-level step (read, skip conditions, warn, write).

func TestAddReadmeBadges_AlreadyPresentNotAddedTwice(t *testing.T) {
	dir := t.TempDir()
	// A README that already carries the GoDoc badge for the module.
	orig := "# cjson\n\n" + badgeBlock("cjson", "\n") + "\n\nText.\n"
	writeTestFile(t, dir, "README.md", orig)

	var errOut strings.Builder
	addReadmeBadges(dir, "cjson", &errOut)

	got, _ := fileOnDisk(t, dir, "README.md")
	if got != orig {
		t.Errorf("README was modified although badges were already present:\n%q", got)
	}
	// Exactly one GoDoc badge, not two.
	if n := strings.Count(got, badgeMarker("cjson")); n != 1 {
		t.Errorf("GoDoc badge marker appears %d times, want 1", n)
	}
}

func TestAddReadmeBadges_NoReadmeNoWarning(t *testing.T) {
	dir := t.TempDir() // no README.md
	var errOut strings.Builder
	addReadmeBadges(dir, "cjson", &errOut)
	if errOut.Len() != 0 {
		t.Errorf("a missing README must not warn, got: %q", errOut.String())
	}
}

func TestAddReadmeBadges_NoTitleWarns(t *testing.T) {
	dir := t.TempDir()
	orig := `<h1 align="center">cjson</h1>` + "\n\nText.\n"
	writeTestFile(t, dir, "README.md", orig)

	var errOut strings.Builder
	addReadmeBadges(dir, "cjson", &errOut)

	if !strings.Contains(errOut.String(), "no recognizable title") {
		t.Errorf("expected a no-title warning, got: %q", errOut.String())
	}
	got, _ := fileOnDisk(t, dir, "README.md")
	if got != orig {
		t.Errorf("README with no recognizable title must be left unchanged:\n%q", got)
	}
}

func TestAddReadmeBadges_WritesBadges(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, dir, "README.md", "# cjson\n\nText.\n")

	var errOut strings.Builder
	addReadmeBadges(dir, "cjson", &errOut)
	if errOut.Len() != 0 {
		t.Errorf("unexpected warning: %q", errOut.String())
	}
	got, _ := fileOnDisk(t, dir, "README.md")
	want := "# cjson\n\n" + badgeBlock("cjson", "\n") + "\n\nText.\n"
	if got != want {
		t.Errorf("badges not written as expected:\n got:\n%q\nwant:\n%q", got, want)
	}
}

// -----------------------------------------------------------------------------
// End-to-end through Init: the README change lands in the single main commit.

// newTemplateRepoWithReadme builds a template whose main branch carries a
// README with the given content (MODULE_NAME placeholder allowed). It mirrors
// newTemplateRepo but adds the README so the badge step has something to edit.
func newTemplateRepoWithReadme(t *testing.T, readme string) string {
	t.Helper()
	src := t.TempDir()
	runGit(t, src, "init", "-q", "-b", branchMain)

	writeTestFile(t, src, "go.mod", "module "+Placeholder+"\n\ngo 1.27.0\n")
	writeTestFile(t, src, "main.go", "package main\n")
	writeTestFile(t, src, "README.md", readme)
	runGit(t, src, "add", "-A")
	runGit(t, src, "commit", "-q", "-m", "template main")

	runGit(t, src, "checkout", "-q", "--orphan", branchC)
	runGit(t, src, "rm", "-rf", "-q", ".")
	writeTestFile(t, src, "c/go.mod", "module "+Placeholder+"\n\ngo 1.27.0\n")
	writeTestFile(t, src, "c/llcppg.cfg", `{"Name":"`+Placeholder+`"}`+"\n")
	runGit(t, src, "add", "-A")
	runGit(t, src, "commit", "-q", "-m", "template c")
	runGit(t, src, "checkout", "-q", branchMain)

	bare := filepath.Join(t.TempDir(), "template.git")
	cmd := exec.Command("git", "clone", "-q", "--bare", src, bare)
	cmd.Env = testEnv()
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("clone bare template: %v\n%s", err, out)
	}
	return "file://" + bare
}

func TestInit_AddsBadgesInMainCommit(t *testing.T) {
	tmpl := newTemplateRepoWithReadme(t, "# cjson\n\nGo bindings for the cJSON library.\n")
	cache := t.TempDir()
	target := newEmptyTarget(t)

	if _, _, err := runInit(t, target, "cjson", &Config{TemplateURL: tmpl, CacheDir: cache}); err != nil {
		t.Fatalf("Init: %v", err)
	}

	// The README on main carries the badges.
	content, ok := fileOnBranch(t, target, branchMain, "README.md")
	if !ok {
		t.Fatal("README.md missing on main after init")
	}
	if !strings.Contains(content, badgeMarker("cjson")) {
		t.Errorf("badges not added to the main README:\n%s", content)
	}
	if !strings.Contains(content, "# cjson\n\n[![GoDoc]") {
		t.Errorf("badges not placed right after the title:\n%s", content)
	}

	// Still exactly one commit on main: the README edit is part of it, not a
	// separate commit.
	if count := strings.TrimSpace(mustGit(t, target, "rev-list", "--count", branchMain)); count != "1" {
		t.Errorf("main has %s commits, want 1 (badge edit must share the main commit)", count)
	}
	// The working tree is clean: the badge edit was committed, not left staged.
	if status := strings.TrimSpace(mustGit(t, target, "status", "--porcelain")); status != "" {
		t.Errorf("working tree not clean after init:\n%s", status)
	}
}

func TestInit_InferredNameInBadges(t *testing.T) {
	tmpl := newTemplateRepoWithReadme(t, "# title\n\nText.\n")
	cache := t.TempDir()
	target := filepath.Join(t.TempDir(), "cjson")
	if err := os.MkdirAll(target, 0755); err != nil {
		t.Fatal(err)
	}
	runGit(t, target, "init", "-q", "-b", branchMain)

	if _, _, err := runInit(t, target, "", &Config{TemplateURL: tmpl, CacheDir: cache}); err != nil {
		t.Fatalf("Init with inferred module name: %v", err)
	}
	content, ok := fileOnBranch(t, target, branchMain, "README.md")
	if !ok {
		t.Fatal("README.md missing on main")
	}
	// The inferred name (the directory base, "cjson") fills the badges.
	if !strings.Contains(content, badgeMarker("cjson")) {
		t.Errorf("inferred module name not used in badges:\n%s", content)
	}
}

func TestInit_NoReadmeOnMainIsFine(t *testing.T) {
	// The default template helper has no README on main; init must still succeed
	// and leave no README behind.
	tmpl := newTemplateRepo(t)
	cache := t.TempDir()
	target := newEmptyTarget(t)

	_, stderr, err := runInit(t, target, "cjson", &Config{TemplateURL: tmpl, CacheDir: cache})
	if err != nil {
		t.Fatalf("Init without a template README: %v", err)
	}
	if strings.Contains(stderr, "badge") {
		t.Errorf("unexpected badge warning when there is no README: %q", stderr)
	}
	if _, ok := fileOnBranch(t, target, branchMain, "README.md"); ok {
		t.Error("a README.md was created where the template had none")
	}
}
