// Code generated by llcppg; DO NOT EDIT.

package py

import (
	c1 "github.com/goplus/lib/c"
	"github.com/goplus/lib/c/pthread"
	_ "unsafe"
)

//go:linkname PY_TIMEOUT_MAX C.PY_TIMEOUT_MAX
var PY_TIMEOUT_MAX c1.LongLong
