// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	"github.com/goplus/lib/c/pthread"
	_ "unsafe"
)

// Return status codes for Python lock acquisition.  Chosen for maximum
// backwards compatibility, ie failure -> 0, success -> 1.
type LockStatus c.Uint

const (
	LOCK_FAILURE  LockStatus = 0
	LOCK_ACQUIRED LockStatus = 1
	LOCK_INTR     LockStatus = 2
)

type ThreadTypeLock uintptr

// When Py_LIMITED_API is not defined, the type layout of Py_tss_t is
// exposed to allow static allocation in the API clients.  Even in this case,
// you must handle TSS keys through API functions due to compatibility.
type X_PyTssT struct {
	X_isInitialized c.Int
	X_key           pthread.Key
}
type X_tssT = X_PyTssT

// PY_TIMEOUT_MAX is the highest usable value (in microseconds) of PY_TIMEOUT_T
// type, and depends on the system threading API.
//
// NOTE: this isn't the same value as `_thread.TIMEOUT_MAX`. The _thread module
// exposes a higher-level API, with timeouts expressed in seconds and
// floating-point numbers allowed.
//
//go:linkname PY_TIMEOUT_MAX C.PY_TIMEOUT_MAX
var PY_TIMEOUT_MAX c.LongLong
