// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	"github.com/goplus/lib/c/pthread"
	_ "unsafe"
)

type PyLockStatus c.Uint

const (
	PY_LOCK_FAILURE  PyLockStatus = 0
	PY_LOCK_ACQUIRED PyLockStatus = 1
	PY_LOCK_INTR     PyLockStatus = 2
)

type PyThreadTypeLock uintptr
type X_PyTssT struct {
	X_isInitialized c.Int
	X_key           pthread.Key
}
type PyTssT = X_PyTssT

//go:linkname PY_TIMEOUT_MAX C.PY_TIMEOUT_MAX
var PY_TIMEOUT_MAX c.LongLong
