// Code generated by llcppg; DO NOT EDIT.

package py

import "github.com/goplus/lib/c"

type PyLockStatus c.Uint

const (
	PY_LOCK_FAILURE  PyLockStatus = 0
	PY_LOCK_ACQUIRED PyLockStatus = 1
	PY_LOCK_INTR     PyLockStatus = 2
)

type PyThreadTypeLock uintptr
type PyTssT = X_PyTssT
