// Code generated by xgo (XGo); DO NOT EDIT.

package main

import (
	"github.com/goplus/cobra/xcmd"
	"github.com/goplus/llcppg/cmd/internal/gencfg"
	"github.com/goplus/llcppg/cmd/internal/genpkg"
	"github.com/goplus/llcppg/cmd/internal/gensig"
	"github.com/goplus/llcppg/cmd/internal/gensym"
	"github.com/goplus/llcppg/cmd/internal/runtest"
	"github.com/goplus/llcppg/cmd/internal/version"
)

const _ = true

type Cmd_gencfg struct {
	xcmd.Command
	*App
}
type Cmd_genpkg struct {
	xcmd.Command
	*App
}
type Cmd_gensig struct {
	xcmd.Command
	*App
}
type Cmd_gensym struct {
	xcmd.Command
	*App
}
type App struct {
	xcmd.App
}
type Cmd_runtest struct {
	xcmd.Command
	*App
}
type Cmd_version struct {
	xcmd.Command
	*App
}
//line cmd/llcppg/main_app.gox:1
func (this *App) MainEntry() {
//line cmd/llcppg/main_app.gox:1:1
	this.Short(`llcppg aims to be a tool for automatically generating LLGo bindings for C/C++ libraries, enhancing the experience of integrating LLGo with C!`)
}
func (this *App) Main() {
	_xgo_obj0 := &Cmd_gencfg{App: this}
	_xgo_obj1 := &Cmd_genpkg{App: this}
	_xgo_obj2 := &Cmd_gensig{App: this}
	_xgo_obj3 := &Cmd_gensym{App: this}
	_xgo_obj4 := &Cmd_runtest{App: this}
	_xgo_obj5 := &Cmd_version{App: this}
	xcmd.Gopt_App_Main(this, _xgo_obj0, _xgo_obj1, _xgo_obj2, _xgo_obj3, _xgo_obj4, _xgo_obj5)
}
//line cmd/llcppg/gencfg_cmd.gox:5
func (this *Cmd_gencfg) Main(_xgo_arg0 string) {
	this.Command.Main(_xgo_arg0)
//line cmd/llcppg/gencfg_cmd.gox:5:1
	this.Use("gencfg")
//line cmd/llcppg/gencfg_cmd.gox:7:1
	this.Short("generate llcpp.cfg")
//line cmd/llcppg/gencfg_cmd.gox:9:1
	this.Run__1(func(args []string) {
//line cmd/llcppg/gencfg_cmd.gox:10:1
		gencfg.Cmd.Run(gencfg.Cmd, args)
	})
}
func (this *Cmd_gencfg) Classfname() string {
	return "gencfg"
}
//line cmd/llcppg/genpkg_cmd.gox:5
func (this *Cmd_genpkg) Main(_xgo_arg0 string) {
	this.Command.Main(_xgo_arg0)
//line cmd/llcppg/genpkg_cmd.gox:5:1
	this.Use("genpkg")
//line cmd/llcppg/genpkg_cmd.gox:7:1
	this.Short("generate a go package by signature information of symbols")
//line cmd/llcppg/genpkg_cmd.gox:9:1
	this.Run__1(func(args []string) {
//line cmd/llcppg/genpkg_cmd.gox:10:1
		genpkg.Cmd.Run(genpkg.Cmd, args)
	})
}
func (this *Cmd_genpkg) Classfname() string {
	return "genpkg"
}
//line cmd/llcppg/gensig_cmd.gox:5
func (this *Cmd_gensig) Main(_xgo_arg0 string) {
	this.Command.Main(_xgo_arg0)
//line cmd/llcppg/gensig_cmd.gox:5:1
	this.Use("gensig")
//line cmd/llcppg/gensig_cmd.gox:7:1
	this.Short("generate signature information of C/C++ symbols")
//line cmd/llcppg/gensig_cmd.gox:9:1
	this.Run__1(func(args []string) {
//line cmd/llcppg/gensig_cmd.gox:10:1
		gensig.Cmd.Run(gensig.Cmd, args)
	})
}
func (this *Cmd_gensig) Classfname() string {
	return "gensig"
}
//line cmd/llcppg/gensym_cmd.gox:5
func (this *Cmd_gensym) Main(_xgo_arg0 string) {
	this.Command.Main(_xgo_arg0)
//line cmd/llcppg/gensym_cmd.gox:5:1
	this.Use("gensym")
//line cmd/llcppg/gensym_cmd.gox:7:1
	this.Short("generate symbol table for a C/C++ library")
//line cmd/llcppg/gensym_cmd.gox:9:1
	this.Run__1(func(args []string) {
//line cmd/llcppg/gensym_cmd.gox:10:1
		gensym.Cmd.Run(gensym.Cmd, args)
	})
}
func (this *Cmd_gensym) Classfname() string {
	return "gensym"
}
//line cmd/llcppg/runtest_cmd.gox:5
func (this *Cmd_runtest) Main(_xgo_arg0 string) {
	this.Command.Main(_xgo_arg0)
//line cmd/llcppg/runtest_cmd.gox:5:1
	this.Use("runtest")
//line cmd/llcppg/runtest_cmd.gox:7:1
	this.Short("run test for llcppg")
//line cmd/llcppg/runtest_cmd.gox:9:1
	this.Run__1(func(args []string) {
//line cmd/llcppg/runtest_cmd.gox:10:1
		runtest.Cmd.Run(runtest.Cmd, args)
	})
}
func (this *Cmd_runtest) Classfname() string {
	return "runtest"
}
//line cmd/llcppg/version_cmd.gox:5
func (this *Cmd_version) Main(_xgo_arg0 string) {
	this.Command.Main(_xgo_arg0)
//line cmd/llcppg/version_cmd.gox:5:1
	this.Use("version")
//line cmd/llcppg/version_cmd.gox:7:1
	this.Short("Print llcppg version")
//line cmd/llcppg/version_cmd.gox:9:1
	this.Run__1(func(args []string) {
//line cmd/llcppg/version_cmd.gox:10:1
		version.Cmd.Run(version.Cmd, args)
	})
}
func (this *Cmd_version) Classfname() string {
	return "version"
}
func main() {
	new(App).Main()
}
