/*
 * Copyright (c) 2026 The XGo Authors (xgo.dev). All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package tool

import (
	"encoding/json"
	"fmt"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/goplus/gogen"
	"github.com/goplus/gogen/packages"
	"github.com/goplus/gogen/packages/cache"
	"github.com/goplus/llcppg/cl"
	"github.com/goplus/llcppg/clang"
	"github.com/goplus/llcppg/tool/pputil"
	"github.com/goplus/mod"
	"github.com/goplus/mod/xgomod"
	"github.com/qiniu/x/errors"
)

const (
	DbgFlagLoadSource = 1 << iota
	DbgFlagImport
	DbgFlagAll = DbgFlagLoadSource | DbgFlagImport
)

var (
	debugLoadSource bool
	debugImport     bool
)

func SetDebug(flags int) {
	debugLoadSource = (flags & DbgFlagLoadSource) != 0
	debugImport = (flags & DbgFlagImport) != 0
}

// -----------------------------------------------------------------------------

var (
	// GeneratedHeader is the header comment for llcppg generated Go files.
	GeneratedHeader = "// Code generated by llcppg; DO NOT EDIT.\n\n"
)

var (
	// ErrStdlibRequired is returned when the stdlib field is not specified in the
	// configuration.
	ErrStdlibRequired = errors.New("stdlib is required")
)

// -----------------------------------------------------------------------------

type Config struct {
	Name        string            `json:"Name"`        // required
	Language    string            `json:"Language"`    // c, c++, etc. required
	Dir         string            `json:"Dir"`         // dir or dir/... (recursive), required
	Stdlib      string            `json:"Stdlib"`      // C stdlib include dir, required
	LLGoPackage string            `json:"LLGoPackage"` // optional
	CFlags      string            `json:"CFlags"`      // optional
	Deps        []string          `json:"Deps"`        // dependencies (package paths), optional
	Class       []string          `json:"Class"`       // typedef names to be treated as classes
	NonClass    []string          `json:"NonClass"`    // typedef names to be treated as non-classes
	FuncPrefix  []string          `json:"FuncPrefix"`  // global function prefix to remove
	EnumPrefix  []string          `json:"EnumPrefix"`  // enum value prefix to remove
	TypePrefix  []string          `json:"TypePrefix"`  // type prefix to remove
	TypeAbbr    map[string]string `json:"TypeAbbr"`    // Go type name to its abbr, used in function names
	Rename      map[string]string `json:"Rename"`      // renaming of C/C++ names to Go names
	Ignore      []string          `json:"Ignore"`      // C/C++ names to ignore
}

// LoadConf loads the llcppg configuration.
func LoadConf(filename string) (cfg Config, err error) {
	b, err := os.ReadFile(filename)
	if err != nil {
		return
	}

	err = json.Unmarshal(b, &cfg)
	return
}

// Lang returns the language of the configuration.
func (cfg *Config) Lang() (lang cl.Language, ok bool) {
	switch cfg.Language {
	case "c":
		return cl.LanguageC, true
	case "c++":
		return cl.LanguageCXX, true
	default:
		return 0, false
	}
}

const includeSuffix = string(os.PathSeparator) + "include"

// topHeaders lists the top-level header files according to the configuration. If the
// Dir field ends with "/...", it will recursively list all header files in the directory
// and its subdirectories. includeDirs[0] will be set to the include directory for the
// package.
func topHeaders(dir, workDir string, includeDirs []string) (headerFiles []string, err error) {
	recursive := strings.HasSuffix(dir, "/...")
	if recursive {
		dir = dir[:len(dir)-4]
	}
	if !filepath.IsAbs(dir) {
		dir = filepath.Join(workDir, dir)
	}
	incDir := dir
	if pos := strings.LastIndex(incDir, includeSuffix); pos >= 0 {
		incDir = incDir[:pos+len(includeSuffix)]
	}
	includeDirs[0] = incDir
	if debugLoadSource {
		log.Println("==> includeDirs:", includeDirs)
	}
	return pputil.TopHeaders(dir, recursive, false, includeDirs)
}

// NewPackage loads the source files and converts them into a Go package according to the
// configuration.
func (cfg *Config) NewPackage(pkgPath, workDir string, index clang.Index) (ret cl.Package, lang cl.Language, err error) {
	lang, ok := cfg.Lang()
	if !ok {
		err = fmt.Errorf("invalid language: %q", cfg.Language)
		return
	}

	workDir, err = filepath.Abs(workDir)
	if err != nil {
		return
	}

	stdlibDir := cfg.Stdlib
	if stdlibDir == "" {
		err = ErrStdlibRequired
		return
	}
	if !filepath.IsAbs(stdlibDir) {
		stdlibDir = filepath.Join(workDir, stdlibDir)
	}

	if debugLoadSource {
		log.Println("==> workDir:", workDir)
	}

	mod, err := LoadModuleFrom(workDir)
	if err != nil {
		return
	}

	fset := token.NewFileSet()
	imp := packages.NewImporter(fset, workDir)

	deps := cfg.Deps
	if len(deps) > 0 {
		c := cache.New(pkgHash)
		c.Prepare(workDir, deps...)
		imp.SetCache(c)
	}

	includeDirs, pkgPaths := mod.includeDirs(imp, deps, 2)
	includeDirs[1] = stdlibDir
	pkgPaths[0] = pkgPath
	pkgPaths[1] = "github.com/goplus/lib/c"

	// includeDirs[0] is set by topHeaders
	topHeaders, err := topHeaders(cfg.Dir, workDir, includeDirs)
	if err != nil {
		return
	}

	files, err := ParseSources(index, topHeaders, includeDirs, cfg.Language)
	if err != nil {
		return
	}
	defer DisposeSources(files)

	if debugLoadSource {
		dumpSources(topHeaders, files)
	}

	ret, err = cl.NewPackage(pkgPath, cfg.Name, files, &cl.Config{
		Fset:            fset,
		Importer:        imp,
		LLGoPackage:     cfg.LLGoPackage,
		Language:        lang,
		CFlags:          cfg.CFlags,
		Class:           cfg.Class,
		NonClass:        cfg.NonClass,
		FuncPrefix:      cfg.FuncPrefix,
		EnumPrefix:      cfg.EnumPrefix,
		TypePrefix:      cfg.TypePrefix,
		TypeAbbr:        cfg.TypeAbbr,
		Rename:          cfg.Rename,
		Ignore:          cfg.Ignore,
		DefaultGoFile:   "llcppg.i.go",
		GenMultiGoFiles: true,
		UseStdRecvName:  true,
		NameLookup:      nil,
		PubFileLookup:   mod.PubFileLookup,
		PackageOf: func(headerFile string) (pkgPath string, ok bool) {
			for i, includeDir := range includeDirs {
				if strings.HasPrefix(headerFile, includeDir) {
					return pkgPaths[i], true
				}
			}
			return
		},
	})
	return
}

func pkgHash(pkgPath string, self bool) string {
	// don't need calc hash since we only load all packages once.
	return cache.HashSkip
}

// -----------------------------------------------------------------------------

// Module represents a llcppg module.
type Module struct {
	mod *xgomod.Module
}

// LoadModuleFrom loads a llcppg module from the specified directory.
func LoadModuleFrom(dir string) (ret Module, err error) {
	_, gomod, err := mod.FindGoMod(dir)
	if err != nil {
		return
	}
	m, err := xgomod.LoadFrom(gomod, "")
	return Module{mod: m}, err
}

// PubFileLookup looks up the public file for the given package.
func (p Module) PubFileLookup(pkgPath string) (pubFile string, ok bool) {
	pkg, err := p.mod.Lookup(pkgPath)
	if err == nil {
		pubFile, ok = filepath.Join(pkg.Dir, "llcppg.pub"), true
	}
	return
}

// includeDirs returns the include directories and package paths for the given dependencies.
// The reserved parameter specifies the number of reserved slots in the returned slices.
func (p Module) includeDirs(imp *packages.Importer, deps []string, reserved int) (incDirs, pkgPaths []string) {
	incDirs = make([]string, reserved, len(deps)+reserved)
	pkgPaths = make([]string, reserved, len(deps)+reserved)
	for _, dep := range deps {
		pkgTypes, err := imp.Import(dep)
		if err == nil {
			if o := pkgTypes.Scope().Lookup("LLGoFiles"); o != nil {
				pkg, err := p.mod.Lookup(dep)
				if err == nil {
					incDirs = append(incDirs, filepath.Join(pkg.Dir, "_wrap/include"))
					pkgPaths = append(pkgPaths, dep)
				}
			}
		}
	}
	return
}

// -----------------------------------------------------------------------------

// ParseSources parses the given source files and returns the translation units corresponding
// to those files.
func ParseSources(index clang.Index, headerFiles, includeDirs []string, lang string) ([]cl.Source, error) {
	n := len(includeDirs)
	flags := make([]string, n+2)
	for i, dir := range includeDirs {
		flags[i] = "-I" + dir
	}
	flags[n] = "-x"
	flags[n+1] = lang
	files := make([]cl.Source, len(headerFiles))
	for i, headerFile := range headerFiles {
		tu, e := index.ParseTranslationUnit(clang.DetailedPreprocessingRecord, headerFile, flags...)
		if e != nil {
			return nil, e
		}
		files[i] = tu
	}
	return files, nil
}

// DisposeSources disposes the given translation units.
func DisposeSources(sources []cl.Source) {
	for _, f := range sources {
		f.Dispose()
	}
}

// -----------------------------------------------------------------------------

// Gen generates Go files from the C/C++ header files and llcppg.cfg in the specified
// source directory and writes them to the destination directory. It uses the provided
// clang index for parsing.
func Gen(destDir, srcDir string, index clang.Index) (err error) {
	cfg, err := LoadConf(filepath.Join(srcDir, "llcppg.cfg"))
	if err != nil {
		return
	}

	err = os.MkdirAll(destDir, 0755)
	if err != nil {
		return
	}

	pkg, _, err := cfg.NewPackage("", srcDir, index)
	if err != nil {
		return
	}

	var errs errors.List
	var old = gogen.GeneratedHeader
	defer func() {
		gogen.GeneratedHeader = old
	}()
	gogen.GeneratedHeader = GeneratedHeader
	pkg.ForEachFile(func(fname string, file *gogen.File) {
		if file.Empty() {
			return // skip empty Go files
		}
		goFile := filepath.Join(destDir, fname)
		e := pkg.WriteFile(goFile, fname)
		if e != nil {
			errs.Add(e)
		}
	})
	return errs.ToError()
}

// -----------------------------------------------------------------------------
