/*
 * Copyright (c) 2026 The XGo Authors (xgo.dev). All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package tool

import (
	"fmt"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/goplus/gogen"
	"github.com/goplus/gogen/packages"
	"github.com/goplus/gogen/packages/cache"
	"github.com/goplus/llcppg/cl"
	"github.com/goplus/llcppg/clang"
	"github.com/goplus/llcppg/tool/pputil"
	"github.com/goplus/mod"
	"github.com/goplus/mod/xgomod"
	"github.com/qiniu/x/errors"
)

const (
	DbgFlagSettings = 1 << iota
	DbgFlagAll      = DbgFlagSettings
)

var (
	debugSettings bool
)

func SetDebug(flags int) {
	debugSettings = (flags & DbgFlagSettings) != 0
}

// -----------------------------------------------------------------------------

var (
	// GeneratedHeader is the header comment for llcppg generated Go files.
	GeneratedHeader = "// Code generated by llcppg; DO NOT EDIT.\n\n"
)

var (
	// ErrDirRequired is returned when the Dir field in the configuration is empty.
	// It indicates that the directory containing the header files is required.
	ErrDirRequired = errors.New("Dir (contains the header files) is required")
)

// -----------------------------------------------------------------------------

const includeSuffix = string(os.PathSeparator) + "include"

// NewPackage loads the source files and converts them into a Go package according to the
// configuration.
func (cfg *Config) NewPackage(pkgPath, workDir string, index clang.Index) (ret cl.Package, lang cl.Language, err error) {
	lang, ok := cfg.Lang()
	if !ok {
		err = fmt.Errorf("invalid language: %q", cfg.Language)
		return
	}

	if cfg.Dir == "" {
		err = ErrDirRequired
		return
	}

	workDir, err = filepath.Abs(workDir)
	if err != nil {
		return
	}
	if debugSettings {
		log.Println("==> workDir:", workDir)
	}

	mod, err := LoadModuleFrom(workDir)
	if err != nil {
		return
	}

	fset := token.NewFileSet()
	imp := packages.NewImporter(fset, workDir)

	deps := cfg.Deps
	if len(deps) > 0 {
		c := cache.New(pkgHash)
		c.Prepare(workDir, deps...)
		imp.SetCache(c)
	}

	stdlibDirs := cfg.StdlibDirs(workDir)
	if debugSettings {
		log.Println("==> stdlibDirs:", stdlibDirs)
	}

	incDirs, pkgPaths := mod.includeDirs(imp, deps, 1, 1+len(stdlibDirs))
	for _, stdlibDir := range stdlibDirs {
		incDirs = append(incDirs, stdlibDir)
		pkgPaths = append(pkgPaths, "github.com/goplus/lib/c")
	}

	dir := cfg.Dir
	recursive := strings.HasSuffix(dir, "/...")
	if recursive {
		dir = dir[:len(dir)-4]
	}
	if !filepath.IsAbs(dir) {
		dir = filepath.Join(workDir, dir)
	}
	if debugSettings {
		log.Println("==> srcDir:", dir)
	}

	incDir := dir
	if pos := strings.LastIndex(incDir, includeSuffix); pos >= 0 {
		incDir = incDir[:pos+len(includeSuffix)]
	}
	incDirs[0] = incDir
	pkgPaths[0] = pkgPath

	if debugSettings {
		log.Println("==> includeDirs:", incDirs)
	}

	topHeaders, err := pputil.TopHeaders(dir, recursive, false, incDirs)
	if err != nil {
		return
	}

	files, err := ParseSources(index, topHeaders, incDirs, cfg.Language)
	if err != nil {
		return
	}
	defer DisposeSources(files)

	ret, err = cl.NewPackage(pkgPath, cfg.Name, files, &cl.Config{
		Fset:                   fset,
		Importer:               imp,
		LLGoPackage:            cfg.LLGoPackage,
		Language:               lang,
		CFlags:                 cfg.CFlags,
		Class:                  cfg.Class,
		NonClass:               cfg.NonClass,
		FuncPrefix:             cfg.FuncPrefix,
		VarPrefix:              cfg.VarPrefix,
		EnumPrefix:             cfg.EnumPrefix,
		MacroPrefix:            cfg.MacroPrefix,
		TypePrefix:             cfg.TypePrefix,
		TypeAbbr:               cfg.TypeAbbr,
		Rename:                 cfg.Rename,
		Ignore:                 cfg.Ignore,
		DefaultGoFile:          "llcppg.i.go",
		SourceHeaderFilePrefix: dir + string(os.PathSeparator),
		GenMultiGoFiles:        true,
		UseStdRecvName:         true,
		NameLookup:             nil,
		PubFileLookup:          mod.PubFileLookup,
		PackageOf: func(headerFile string) (pkgPath string, ok bool) {
			for i, includeDir := range incDirs {
				if strings.HasPrefix(headerFile, includeDir) {
					return pkgPaths[i], true
				}
			}
			return
		},
	})
	return
}

func pkgHash(pkgPath string, self bool) string {
	// don't need calc hash since we only load all packages once.
	return cache.HashSkip
}

// -----------------------------------------------------------------------------

// Module represents a llcppg module.
type Module struct {
	mod *xgomod.Module
}

// LoadModuleFrom loads a llcppg module from the specified directory.
func LoadModuleFrom(dir string) (ret Module, err error) {
	_, gomod, err := mod.FindGoMod(dir)
	if err != nil {
		return
	}
	m, err := xgomod.LoadFrom(gomod, "")
	return Module{mod: m}, err
}

// PubFileLookup looks up the public file for the given package.
func (p Module) PubFileLookup(pkgPath string) (pubFile string, ok bool) {
	pkg, err := p.mod.Lookup(pkgPath)
	if err == nil {
		pubFile, ok = filepath.Join(pkg.Dir, "llcppg.pub"), true
	}
	return
}

// includeDirs returns the include directories and package paths for the given dependencies.
// The reserved parameter specifies the number of reserved slots in the returned slices.
func (p Module) includeDirs(imp *packages.Importer, deps []string, n, reserved int) (incDirs, pkgPaths []string) {
	incDirs = make([]string, n, len(deps)+reserved)
	pkgPaths = make([]string, n, len(deps)+reserved)
	for _, dep := range deps {
		pkgTypes, err := imp.Import(dep)
		if err == nil {
			if o := pkgTypes.Scope().Lookup("LLGoFiles"); o != nil {
				pkg, err := p.mod.Lookup(dep)
				if err == nil {
					incDirs = append(incDirs, filepath.Join(pkg.Dir, "_wrap/include"))
					pkgPaths = append(pkgPaths, dep)
				}
			}
		}
	}
	return
}

// -----------------------------------------------------------------------------

// ParseSources parses the given source files and returns the translation units corresponding
// to those files.
func ParseSources(index clang.Index, headerFiles, includeDirs []string, lang string) ([]cl.Source, error) {
	n := len(includeDirs)
	flags := make([]string, n+2)
	for i, dir := range includeDirs {
		flags[i] = "-I" + dir
	}
	flags[n] = "-x"
	flags[n+1] = lang
	files := make([]cl.Source, len(headerFiles))
	for i, headerFile := range headerFiles {
		tu, e := index.ParseTranslationUnit(clang.DetailedPreprocessingRecord, headerFile, flags...)
		if e != nil {
			return nil, e
		}
		files[i] = tu
	}
	return files, nil
}

// DisposeSources disposes the given translation units.
func DisposeSources(sources []cl.Source) {
	for _, f := range sources {
		f.Dispose()
	}
}

// -----------------------------------------------------------------------------

// Gen generates Go files from the C/C++ header files and llcppg.cfg in the specified
// source directory and writes them to the destination directory. It uses the provided
// clang index for parsing.
func Gen(destDir, srcDir string, index clang.Index) (err error) {
	cfg, err := LoadConf(filepath.Join(srcDir, "llcppg.cfg"))
	if err != nil {
		return
	}

	err = os.MkdirAll(destDir, 0755)
	if err != nil {
		return
	}

	pkg, _, err := cfg.NewPackage("", srcDir, index)
	if err != nil {
		return
	}

	var errs errors.List
	var old = gogen.GeneratedHeader
	defer func() {
		gogen.GeneratedHeader = old
	}()
	gogen.GeneratedHeader = GeneratedHeader
	pkg.ForEachFile(func(fname string, file *gogen.File) {
		if file.Empty() {
			return // skip empty Go files
		}
		goFile := filepath.Join(destDir, fname)
		e := pkg.WriteFile(goFile, fname)
		if e != nil {
			errs.Add(e)
		}
	})
	return errs.ToError()
}

// -----------------------------------------------------------------------------
