// Code generated by llcppg; DO NOT EDIT.

package system

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

//go:linkname SysMemoryFence C._ZN4llvm3sys11MemoryFenceEv
func SysMemoryFence()

//go:linkname SysCompareAndSwap C._ZN4llvm3sys14CompareAndSwapEPViii
func SysCompareAndSwap(ptr *c.Int, new_value c.Int, old_value c.Int) c.Int
