name: "Setup llcppg"
description: "Install dependencies, set up Go, set up LLGo, install llcppg"
inputs:
  go:
    description: "Go version to install"
    default: "1.23"
  llvm:
    description: "LLVM version to install (e.g. 18)"
    default: "19"
  llgo:
    description: "LLGo version (e.g., v0.11.6)"
    default: "v0.11.6"
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - name: Set up Go
    uses: actions/setup-go@v4
    with:
      go-version: ${{inputs.go}}
  - name: Install dependencies (macOS)
    if: runner.os == 'macOS'
    shell: bash
    run: |
      brew install bdw-gc openssl libffi libuv
      brew install zlib # for llgo test .
      brew link --force zlib # for llgo test .
      brew link --force libffi
  - name: Install dependencies (Linux)
    shell: bash
    if: runner.os == 'Linux'
    run: |
      sudo apt-get update
      sudo apt-get install -y pkg-config libgc-dev libssl-dev zlib1g-dev libffi-dev libuv1-dev
  - name: Download and Install LLGo
    shell: bash
    run: |
      # Determine platform and architecture
      OS=$(uname -s | tr '[:upper:]' '[:lower:]')
      ARCH=$(uname -m)

      if [ "$OS" = "darwin" ]; then
        PLATFORM="darwin"
      elif [ "$OS" = "linux" ]; then
        PLATFORM="linux"
      else
        echo "Unsupported OS: $OS"
        exit 1
      fi

      if [ "$ARCH" = "x86_64" ]; then
        ARCH="amd64"
      elif [ "$ARCH" = "aarch64" ] || [ "$ARCH" = "arm64" ]; then
        ARCH="arm64"
      else
        echo "Unsupported architecture: $ARCH"
        exit 1
      fi

      # Download and extract llgo
      VERSION="${{inputs.llgo}}"
      # Remove 'v' prefix from version for filename
      VERSION_NUM="${VERSION#v}"
      FILENAME="llgo${VERSION_NUM}.${PLATFORM}-${ARCH}.tar.gz"
      URL="https://github.com/goplus/llgo/releases/download/${VERSION}/${FILENAME}"

      echo "Downloading llgo from: $URL"
      wget -q "$URL" -O llgo.tar.gz

      # Extract to .llgo directory
      mkdir -p .llgo
      tar -xzf llgo.tar.gz -C .llgo --strip-components=1
      rm llgo.tar.gz

      # Set LLGO_ROOT and add to PATH
      export LLGO_ROOT="$GITHUB_WORKSPACE/.llgo"
      echo "LLGO_ROOT=$LLGO_ROOT" >> $GITHUB_ENV
      echo "$LLGO_ROOT/bin" >> $GITHUB_PATH

      echo "LLGo installed successfully to $LLGO_ROOT"
      llgo version || echo "llgo version check will be available after PATH update"
  - name: Build
    shell: bash
    run: go build -v ./...

  - name: Install llcppg modules
    shell: bash
    run: |
      echo "Using LLGO_ROOT: $LLGO_ROOT"
      llgo install ./_xtool/llclang
      bash ./install.sh
