name: "Setup llcppg"
description: "Install dependencies, set up Go, set up LLGo, install llcppg"
inputs:
  go:
    description: "Go version to install"
    default: "1.23"
  llvm:
    description: "LLVM version to install (e.g. 18)"
    default: "19"
  llgo:
    description: "LLGo git ref or tag"
    default: "87c7b65223eea16ade3ad1de4079bf2a20d20b1b"
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - name: Checkout LLGo
    uses: actions/checkout@v4
    with:
      repository: 'goplus/llgo'
      path: '.llgo'
      ref: ${{inputs.llgo}}
  - name: Set up Go
    uses: actions/setup-go@v4
    with:
      go-version: ${{inputs.go}}
  - name: Install dependencies
    if: runner.os == 'macOS'
    shell: bash
    run: |
      brew update
      brew install llvm@${{inputs.llvm}} bdw-gc openssl libffi libuv lld@${{inputs.llvm}}
      brew install zlib # for llgo test .
      brew link --force zlib # for llgo test .
      brew link --force libffi
      echo "$(brew --prefix llvm@${{inputs.llvm}})/bin" >> $GITHUB_PATH
      echo "$(brew --prefix lld@${{inputs.llvm}})/bin" >> $GITHUB_PATH
      # llcppg dependencies
      brew install cjson
  - name: Install dependencies
    shell: bash
    if: runner.os == 'Linux'
    run: |
      echo "deb http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs)-${{inputs.llvm}} main" | sudo tee /etc/apt/sources.list.d/llvm.list
      wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      sudo apt-get update
      sudo apt-get install -y llvm-${{inputs.llvm}}-dev clang-${{inputs.llvm}} libunwind-dev libclang-${{inputs.llvm}}-dev lld-${{inputs.llvm}} pkg-config libgc-dev libssl-dev zlib1g-dev libffi-dev libcjson-dev libuv1-dev
      echo "/usr/lib/llvm-${{inputs.llvm}}/bin" >> $GITHUB_PATH
  - name: Install LLGo
    shell: bash
    working-directory: .llgo
    run: |
      go install -v ./cmd/llgo/...
      export LLGO_ROOT=$GITHUB_WORKSPACE/.llgo
      echo "LLGO_ROOT=$LLGO_ROOT" >> $GITHUB_ENV
  - name: Build
    shell: bash
    run: go build -v ./...

  - name: Install llcppg modules
    shell: bash
    run: |
      echo "Using LLGO_ROOT: $LLGO_ROOT"
      llgo install ./_xtool/llclang
      bash ./install.sh
