name: Test Result End2End

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:

  test:
    strategy:
      matrix:
        os:
          - macos-13
          - macos-latest
          - ubuntu-24.04
          - ubuntu-24.04-arm
        llvm: [19]
        llgo: [132e240e87828a8575dd5ad7978f74014142583c]
        go: [1.23]
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - name: Setup llcppg environment
      uses: ./.github/actions/setup-llcppg
      with:
        go: ${{ matrix.go }}
        llvm: ${{ matrix.llvm }}
        llgo: ${{ matrix.llgo }}

    - name: Install Conan
      if: startsWith(matrix.os, 'macos')
      run: brew install conan

    - name: Install Conan
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get install -y python3 python3-pip
        python3 -m pip install conan

    - name: Set up Conan
      run: conan profile detect

    - name: Setup Log directory
      run: echo "LLCPPG_TEST_LOG_DIR=$(mktemp -d)" >> $GITHUB_ENV

    - name: Turn off filemode diff
      run: git config --global core.fileMode false

    - name: Test End2End
      working-directory: _cmptest
      run: |
        # increase the test timeout to avoid conan installation timeout occasionally
        go test -v -timeout 30m .

    - name: Upload Logs to Artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{matrix.os}}-log
        path: ${{env.LLCPPG_TEST_LOG_DIR}}
        retention-days: 1
        include-hidden-files: true
