name: Test Demo With Generated Pkgs

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  test:
    strategy:
      matrix:
        os:
          - macos-15-intel
          - macos-latest
          - ubuntu-latest
          - ubuntu-24.04-arm
        llvm: [19]
        llgo: [e4218f90d7926d31c1ffae3965a4e36228d38fd2]
        go: [1.23]
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v5
    - name: Setup llcppg environment
      uses: ./.github/actions/setup-llcppg
      with:
        go: ${{ matrix.go }}
        llvm: ${{ matrix.llvm }}
        llgo: ${{ matrix.llgo }}
    - name: Setup Log directory
      run: echo "LLCPPG_TEST_LOG_DIR=$(mktemp -d)" >> $GITHUB_ENV
    - name: Test demos with generated pkgs
      if: startsWith(matrix.os, 'macos')
      run: |
        # install demo's lib
        brew install cjson lua zlib isl libgpg-error raylib z3 sqlite3 gmp libxml2 libxslt

        # Detect Homebrew prefix for different macOS versions and architectures
        HOMEBREW_PREFIX=$(brew --prefix)

        export PKG_CONFIG_PATH="$HOMEBREW_PREFIX/opt/zlib/lib/pkgconfig"
        export PKG_CONFIG_PATH="$HOMEBREW_PREFIX/opt/sqlite/lib/pkgconfig:$PKG_CONFIG_PATH"
        export PKG_CONFIG_PATH="$HOMEBREW_PREFIX/opt/libxml2/lib/pkgconfig:$PKG_CONFIG_PATH"
        export PKG_CONFIG_PATH="$HOMEBREW_PREFIX/opt/libxslt/lib/pkgconfig:$PKG_CONFIG_PATH"
        pkg-config --cflags --libs sqlite3
        pkg-config --cflags --libs libxslt
        llcppgtest -demos ./_llcppgtest

    - name: Test demos with generated pkgs
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        # install demo's lib
        sudo apt install libcjson-dev liblua5.4-dev libsqlite3-dev libgmp-dev libgpg-error-dev zlib1g-dev libisl-dev libz3-dev -y
        llcppgtest -demos ./_llcppgtest
    - name: Upload Logs to Artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{matrix.os}}-log
        path: ${{env.LLCPPG_TEST_LOG_DIR}}
        retention-days: 1
        include-hidden-files: true

