# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:

  test:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-24.04
        llvm: [19]
        llgo: [450a3637e44f73de2cb05ddacc77f6886877c69b]
        go: [1.23]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - name: Setup llcppg environment
      uses: ./.github/actions/setup-llcppg
      with:
        go: ${{ matrix.go }}
        llvm: ${{ matrix.llvm }}
        llgo: ${{ matrix.llgo }}

    - name: Test xtool
      run: |
        # llgo test ./_xtool/internal/parser/...
        # got go/bin/parser.test: exit code -1

        # check exit code outout for temporary fix
        # with the latest update can exit in llgo test
        # only with llgo test ./... with llgo update
        # https://github.com/goplus/llgo/pull/1128
        bash .github/workflows/llgo_test.sh $(ls -d _xtool/internal/*/)


    - name: Test llcppsymg & llcppsigfetch
      run: |
        llgo cmptest ./_xtool/llcppsigfetch/parse/cvt_test/...

        bash .github/workflows/llgo_test.sh $(ls -d _xtool/llcppsymg/internal/*/)

        # llgo cmptest ./_xtool/llcppsymg/_cmptest/... causes
        # panic: runtime error: index out of range [0] with length 0
        cd _xtool/llcppsymg/_cmptest

        # llgo cmptest ./... cause  lld: error: undefined symbol: sort.init
        # https://github.com/goplus/llgo/issues/944

        llgo cmptest ./symbol_test
        llgo cmptest ./symg_test

        cd ../../../

    - name: Test
      if: ${{!startsWith(matrix.os, 'macos')}}
      run: go test -v ./...

    - name: Test with coverage
      if: startsWith(matrix.os, 'macos')
      run: go test -v -coverprofile="coverage.txt" -covermode=atomic ./...

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        slug: goplus/llcppg

    - name: Test demos
      run: |
        # TODO(lijie): force python3-embed to be linked with python-3.12-embed
        # Currently, python3-embed is python-3.13-embed, doesn't work with pytorch
        # Will remove this after pytorch is fixed.
        pcdir=$HOME/pc
        mkdir -p $pcdir
        libdir=$(pkg-config --variable=libdir python-3.12-embed)
        echo "libdir: $libdir"
        ln -s $libdir/pkgconfig/python-3.12-embed.pc $pcdir/python3-embed.pc
        export PKG_CONFIG_PATH=$pcdir
        bash .github/workflows/test_demo.sh
