name: Check Markdown Links

on:
  push:
    branches: [ "**" ]
    paths:
      - '**.md'
  pull_request:
    branches: [ "**" ]
    paths:
      - '**.md'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Check links in markdown files
      uses: gaurav-nelson/github-action-markdown-link-check@v1